### ISSUE TITLE
[Quest] "The Air Stands Still" in Icecrown is not completeable

### ISSUE THREAD

**Issue by mcorreale1** [wow-mania/Redemption#108]
When you do this quest, killing the boss mobs does not offer you credit for actually killing them. Probably has something to do with the mob that you summon to help kill the bosses.

**Comment by fvicaria** [comment]
If the NPC does more than 50% you do not get credit. Either buff up or get someone to help you.

**Comment by mourasman** [comment]
"If the NPC does more than 50% you do not get credit. Either buff up or get someone to help you."

That mechanic should not apply to quest NPC's, judging from retail's behavior. The way it is, right now, makes these type of quests impossible to do for tanks and healers. Even for DPS characters, you're not supposed to deal more damage than the NPC, otherwise you'll gain aggro and the mob will destroy you... :)

Sure, you can do this if you get someone to help you, but let's not mask this as intended behavior because it's not.
