### ISSUE TITLE
[Quest] It's a Fel Reaver, But with Heart

### ISSUE THREAD

**Issue by Naigio** [wow-mania/Redemption#117]
In Netherstorm you recieve this quest from N.D Meancamp, and when you apply the Fel Zapper to the heart, the fun begins, but nothing happened whatsoever, no mobs spawned and I was also allowed to target the heart, which I'm pretty sure you're not meant to be.

**Comment by Calebrimbor** [comment]
Issue added to the BugTracker for testing. Thank you for your report. 
@ Testers: Please add all details such as links etc.

**Comment by Calebrimbor** [comment]
Confirmed. I've managed to reproduce. Issue is labeled as 'Confirmed' on the BugTracker.

http://www.wow-mania.com/armory/?quest=10309

Nothing happens when you use the Fel Zapper(http://www.wow-mania.com/armory/?item=29447) besides a message: The scrapped Fel Reaver's mechanical heart begins to beat softly. Also, the Heart of the Fel Reaver(http://www.wow-mania.com/armory/?item=29260) should be inside of the Fel Reaver's corpse if I recall well. Now it's laying somewhere else, see this screenshot:

![wowscrnshot_091216_162439](https://cloud.githubusercontent.com/assets/20358867/18439593/4d04d3e6-7906-11e6-85ae-23873cb81997.jpg)

**Comment by wow-mania** [comment]
Fix should be in dev soon.

**Comment by Calebrimbor** [comment]
Status BugTracker set as 'Pending'.

**Comment by Calebrimbor** [comment]
Not yet fixed. The corpse of the Fel Reaver is added, was missing earlier. But after using the quest item you still don't get the reward for the objective

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.
