### ISSUE TITLE
[Quest] Stunning defeat at the ring

### ISSUE THREAD

**Issue by Kalasbyxan** [wow-mania/Redemption#12]
When accepting the quest (http://wow-mania.com/armory/?quest=11300) the event should start if one of the said NPCs aren't already spawned. No mob spawn and the event never start, thus making the quest incompletable. See https://www.youtube.com/watch?v=HzV_Ls-RoSs&feature=youtu.be

**Comment by temjiu** [comment]
Quest still bugged. Here's a snapshot of what it currently looks like: 

![wowscrnshot_070716_114236](https://cloud.githubusercontent.com/assets/20343926/16665370/2ada18f6-4438-11e6-8c1f-60bc19d8d203.jpg)

Note the green glowy spirit things that aren't present in the official version. Also note the extreme amount of Dragonflayer Prisoners lounging around, instead of in cages. and so far I've been standing in the center for 10m+, and no event starting.
