### ISSUE TITLE
[NPC] Bloodscalp Scavenger (id #702) enrage enters infinite cycle

### ISSUE THREAD

**Issue by mourasman** [wow-mania/Redemption#136]
When these little trolls go on low health, they enrage over and over again infinitely. This doesn't have any impact on the gameplay, besides sounding very annoying!

**Comment by fvicaria** [comment]
Not an issue.

**Comment by goldstinger** [comment]
This is still an active bug. It's not game-breaking in the sense (since Enraged does not stack) but it is annoying in all sense whoever runs into one, especially Alliance players paying a visit to Nesingwary's Expedition Camp.

Screenshot of location & the issue in action.
http://i.imgur.com/wrUOm2y.png

**Comment by wow-mania** [comment]
Should be fixed for next release.

**Comment by fvicaria** [comment]
Fixed.
