### ISSUE TITLE
[Quest] The Stones of Vekh'nir

### ISSUE THREAD

**Issue by GMLucetta** [wow-mania/Redemption#296]
http://www.wow-mania.com/armory/?quest=10565

Dertrok (http://www.wow-mania.com/armory/?npc=21496) gives players this quest in which they have to kill Vekh'nir Arrakoa in order to get a Vekh'nir Crystaa (http://www.wow-mania.com/armory/?item=30561) then they have to stand in a purple rune on the ground and use the Vekh'nir Crystal in order to get a Charged Vekh'nir Crystal (http://www.wow-mania.com/armory/?item=30567). Once this is done they return to Dertrok to hand in the quest. 

He has a grey completion ? over his head despite the quest being shown as complete in the players quest log. At the moment GMs have to manually reward the quest for the player. This is not working as intended.

**Comment by poserbiker** [comment]
This one is unique. Everything works but quest is grayed like you don't have the item. But clearly you do. If you add the item to yourself the quest is able to be completed like normal. I looked into the tables for everything and even the spell.dbc and checked any scripts for this spell but nothing looks "Wrong". The quest is fine, I believe the issue is how the spell transforms the item into the new one its not detecting the change? Not 100% sure.
