### ISSUE TITLE
[Quest] Betrayal

### ISSUE THREAD

**Issue by Calebrimbor** [wow-mania/Redemption#302]
http://www.wow-mania.com/armory/?quest=12713

For this quest you'll need to kill Drakuru(http://www.wow-mania.com/armory/?npc=28503) making use of the Scepter of Domination(http://www.wow-mania.com/armory/?item=39664) to place a Blightblood Troll(http://www.wow-mania.com/armory/?npc=28931) under your control. After Drakuru has been defeated Drakuru's Skull(http://www.wow-mania.com/armory/?item=40425) will spawn.

I have received some reports about the skull being unlootable. I've tested it 3 times. The first 2 times no items where looted, trying again and your receive a error 'item is already being used'. The third time it worked. This definitely needs some checks.

**Comment by wow-mania** [comment]
Fixed for next Wednesday. Please confirm.

**Comment by Calebrimbor** [comment]
Fix is confirmed. Status on BugTracker set as 'Fixed'.

**Comment by Dierdrah** [comment]
There's a new issue with the quest.. The Blightblood Trolls that you control by using the scepter now vanish after about 3 minutes, rendering the fight impossible to finish. I used resto talents and still couldn't heal through it.. plus it seems like the pet's auto attacks are not scripted, only the abilities can be used in order to do damage - which makes it even more difficult. Also, Drakuru's ability Blight Fog is constantly under effect, dealing 1k damage every 3 seconds.. With so much damage from everywhere, plus healing the pet, plus the pet disappearing on me, I got killed in less than 2 minutes. Please fix it!
