### ISSUE TITLE
[Raid] Icecrown Citadel  Lady Deathwhisper

### ISSUE THREAD

**Issue by GMSunShield** [wow-mania/Redemption#377]
**Raid:** Icecrown Citadel http://www.wowhead.com/zone=4812/icecrown-citadel

**Boss:** Lady Deathwhisper http://www.wowhead.com/npc=36855/lady-deathwhisper#article

**Adds Event**
-  **25-player:** adds will come from both left and right side - one add will come from the entrance of the room as well. Kill them as quickly as possible and then go back to burning the boss' mana. Kite any Deformed Fanatics, and watch out for adds casting **Dark Martyrdom** - **it means they will come back to life Reanimated in a few seconds. Spellcasters should stick with the Fanatics, and melee - with the Adherents**. When all of the adds are dead, go back to the boss.

**NPC1:** Reanimated Adherent http://www.wow-mania.com/armory/?npc=38010
**NPC2:** Reanimated Fanatic http://www.wow-mania.com/armory/?npc=38009

>**Issue1:** Both adds never spawn in the fight on 10normal / 10heroic / 25normal / 25Heroic after a Adherent or Fanatic cast **Dark Martyrdom** they should come back as a Reanimated Adherent or Reanimated Fanatic. At the moment every add in the fight casts Dark Martyrdom all at the same time witch they should not only One should do this Per add spawn 10 n/h. Two should do this on 25 N/H Per add spawn. when they blow up they do Aoe damage as they should but they do not come back as the Reanimated witch they should after casting Dark Martyrdom and blowing up.

>**Issue2:** (**Boss Spell 10hc25n25h:** Dominate Mind http://www.wowhead.com/spell=71289/dominate-mind
This should also make the target with the debuff Bigger/Taller to make them easyer to see this does not happen witch makes them harder to see.

**Video of the Fight on Retail 25man Normal.**
- https://www.youtube.com/watch?v=J4gtjDQx4W4

**Video of the Fight on Retail 10man Normal.**
- https://www.youtube.com/watch?v=JXTE2VJSJS0

**Comment by Synathy** [comment]
About Issue2: (Boss Spell 10hc25n25h) Dominate Mind: http://www.wowhead.com/spell=71289/dominate-mind
By looking at Winterfall Firewater (Effect # 2) http://www.wow-mania.com/armory/?spell=17038, the size change is being called Apply Aura: Mod Scale (Value : 25) on the armory (or on wowhead, "Apply Aura: Mod Size % Value: 25%") but Dominate Mind on both wowhead and our armory (http://www.wow-mania.com/armory/?spell=71289) doesn't have the effect "Mod Scale".

Another example of Mod Scale aura is Shrink (http://www.wow-mania.com/armory/?spell=7289 ) from many mobs. On the armory, the value is -2147483647 since the victim get smaller instead of bigger while on wowhead, he's being called "Apply Aura: Mod Size % Value: -30%" (http://www.wowhead.com/spell=7289).
