### ISSUE TITLE
[QUEST] Threat from above

### ISSUE THREAD

**Issue by huqboss** [wow-mania/Redemption#463]
Cultist bombardiers not always spawn as 3, sometimes there are only 2, sometimes none or sometimes they just disappear after brainless run into 1 spot evading all attacks.

Time bombs instead just explode are doing constant auto attacks. Also they are invisible (no model?), only red circle when you target them with tab.

http://www.wowhead.com/quest=13788/threat-from-above

**Comment by wow-mania** [comment]
The quest works fine. The issue is that the check to spawn the bombardiers is based on the health of the chillmaws.  That is 75%, 50% and 25% if you drop its health too fast these checks will fail or skip one as you mentioned. I will try to improve it but this is the result of overpowered players doing easy quests.

**Comment by huqboss** [comment]
Main problem is that they despawn after run to some spot, even if started fight with them they just despawned with low hp. Today had to kill Chillmaw 4 times to kill 3 bombardiers. Doing solo 3-man quest shouldn't be counted as killing it too fast.
