### ISSUE TITLE
Wintergrasp

### ISSUE THREAD

**Issue by JarlOfRedemption** [wow-mania/Redemption#526]
Wintergrasp is just beyond broken.

1) Sometimes its just impossible to capture it. The door appears broken but there is still an invisible wall there preventing you access to the orb.

2) The "Tenacity" buff is out of this world. Even when the teams are fair, I have found the opposing team will still, on occasion, get the buff. This is completely unbalanced. It takes a good 3 people to take down almost anyone with this buff, and it procs when its 2v1.

3) Cannons and Machines. Both of these deal a solid 8000 damage a shot, to a player. This is far from right, even against siege machines it's a bit broken. 

These things together make it almost impossible to take wintergrasp from any competent players, especially seeing as how little people actually turn up

**Comment by fvicaria** [comment]
Not true. Wintergrasp is playable and conquerable. Some fixed. Some "as is".

**Comment by Iambugged** [comment]
I've noticed all these too. Cannon damage might be working properly but their damage radius is way too high to the point that you don't even have to aim in order to damage everything. On top of this spirit healers in the zone don't seem to work at all, making people have to either take sickness or fly to their corpse location and it's giving people up to 2 minute resurrect timers which is a major disadvantage.
