### ISSUE TITLE
Weapon not an option in the list for transmog

### ISSUE THREAD

**Issue by Earthliving** [wow-mania/Redemption#533]
The item "Firesoul" is not an option for MH transmog.

**Comment by firedervil1986** [comment]
what is the weapon that u want to use the transmog on ? becauce the sword firesoul is a onehanded weapon and if your weapon is a mainhand weapon it wont work.
http://wotlk.openwow.com/?item=50035
http://wowwiki.wikia.com/wiki/Firesoul
this for example would work since ist both "mainhand" but not 
http://wowwiki.wikia.com/wiki/Felsteel_Longblade since ist a "one-hand"

**Comment by Earthliving** [comment]
The player who addressed this (non) issue was trying to transmog their Mithrios into Firesoul. I see what you are saying. No bug to report then. Thanks

**Comment by wow-mania** [comment]
Transmog list is randomly generated. There is no obligation for the item you expect to appear.
