### ISSUE TITLE
Quest: abduction 11590

### ISSUE THREAD

**Issue by CaitlinGalanodel** [wow-mania/Redemption#57]
http://www.wowhead.com/quest=11590/abduction

It'not possible capture the  the Beryl Sorcerers. They are green e they seem captured already but the quest is necessary to advance with kirin tor Reputation

**Comment by Oriden** [comment]
Can't confirm, tested today on dev server, works fine

**Comment by genasi** [comment]
There is sometimes an issue with the captured Beryl Sorcerers not despawning and then just wanders around the area making it hard to find 1 to capture. If you find a hostile 1, you can capture it with no problems, I dont think this is an issue that can be replicated on the dev server easily as it seems to be caused by other players capturing a sorcerer and somehow turn in the quest without escorting the sorcerer back to the quest npc on Amber Ledge

**Comment by Calebrimbor** [comment]
It works fine, managed to do this quest 5 times in a row
