### ISSUE TITLE
[NPC] Bitter Initiate & Dark Subjugators

### ISSUE THREAD

**Issue by GameMasterAlliria** [wow-mania/Redemption#73]

**Comment by genasi** [comment]
Not sure if its a pathing issue, but the Bitter Initiate(http://wotlk.openwow.com/npc=32238) found in Icecrown aggro and attack through the tents they are using.
In the same area there are a number of Dark Subjugators(http://wotlk.openwow.com/npc=32236) that you cant use the quest item on for the quest Drag and Drop(http://wotlk.openwow.com/quest=13318).
In regard to that quest, there seems to be an issue with the mobs that are supposed to pick up the Dark Subjugators as well, I did the quest yesterday and on 2 occasions the flying mob came down, picked up the subjugator, dropped him immidiately and attacked me instead of flying off with the subjugator. I think that might be the reason for all those bugged Dark Subjugators

**Comment by Calebrimbor** [comment]
Tested again, it's working now. Closing issue
